name: petshop
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - click=8.0.4
  - krb5=1.19.4
  - libedit=3.1.20221030
  - libffi=3.4.2
  - libpq=12.9
  - ncurses=6.4
  - openssl=1.1.1t
  - pip=23.0.1
  - psycopg2=2.9.3
  - python=3.10.11
  - python-dotenv=0.21.0
  - readline=8.2
  - setuptools=66.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - faker=18.6.2